export default {
  nav: { features: 'Features', pricing: 'Price', login: 'Log In', getStarted: 'Start Free' },
  hero: { title: 'Facebook Page ko Minutes mein High-Converting Ads mein Badlein', subtitle: 'Facebook advertisers, video creators aur live streamers ke liye AI-powered marketing tools.', cta: 'Muft Shuru Karen', ctaSub: 'Credit card ki jaroorat nahi' },
  features: { title: 'Aapko Jo Chahiye Sab Kuch', analysis: { title: 'Page Analysis', desc: 'AI se kisi bhi Facebook page ka analysis karen.' }, copy: { title: 'Copy Generator', desc: '2 versions mein title, body aur CTA banayein.' }, landing: { title: 'Landing Page Builder', desc: 'Poora HTML page preview ke sath banayein.' }, video: { title: 'Video Generation', desc: 'Product ke liye AI video banayein.' } },
  pricing: { title: 'Simple aur Transparent Pricing', subtitle: 'Muft shuru karen, zaroorat padne par upgrade karen.', starter: { name: 'Starter', price: '$19', period: '/maah', tokens: '50,000 AI tokens', videos: '5 video', files: '3 brand files', support: 'Email support' }, pro: { name: 'Pro', price: '$49', period: '/maah', tokens: '200,000 AI tokens', videos: '20 video', files: '10 brand files', support: 'Priority email support', badge: 'Sabse Popular' }, enterprise: { name: 'Enterprise', price: 'Custom', cta: 'Sampark Karen', tokens: 'Unlimited AI tokens', videos: 'Unlimited video', files: 'Unlimited brand files', support: 'Dedicated support' }, cta: 'Shuru Karen' },
  tokens: { title: 'Aur Token Chahiye?', subtitle: 'Upyog ke anusar bhugtan karen. Token kabhi expire nahi hote.', small: { name: 'Chhota Pack', price: '$9', tokens: '20,000 tokens' }, medium: { name: 'Madhyam Pack', price: '$19', tokens: '50,000 tokens' }, large: { name: 'Bada Pack', price: '$39', tokens: '120,000 tokens' }, cta: 'Abhi Khariden' },
  contact: { title: 'Enterprise Sales se Sampark Karen', name: 'Poora Naam', email: 'Email Pata', message: 'Humein apni zarooraten batayein', submit: 'Sandesh Bhejen', success: 'Sandesh bhej diya! Hum 24 ghanton mein jawab denge.', error: 'Bhejna fail.' },
  footer: { rights: '© 2026 AI Marketing OS. Sarvaadhikar surakshit.', contact: 'Sampark' },
}
