export default {
  nav: { features: 'Fitur', pricing: 'Harga', login: 'Masuk', getStarted: 'Mulai Gratis' },
  hero: { title: 'Ubah Halaman Facebook Mana Pun Menjadi Iklan Konversi Tinggi — Dalam Menit', subtitle: 'Alat pemasaran bertenaga AI untuk pengiklan Facebook, kreator video, dan penyiar langsung.', cta: 'Mulai Gratis', ctaSub: 'Tidak perlu kartu kredit' },
  features: { title: 'Semua Yang Anda Butuhkan', analysis: { title: 'Analisis Halaman', desc: 'Analisis halaman Facebook dengan AI.' }, copy: { title: 'Generator Teks', desc: 'Buat 2 versi judul, teks, dan CTA.' }, landing: { title: 'Pembuat Landing Page', desc: 'Buat halaman HTML lengkap dengan pratinjau.' }, video: { title: 'Buat Video', desc: 'Buat video AI untuk produk.' } },
  pricing: { title: 'Harga Sederhana & Transparan', subtitle: 'Mulai gratis, upgrade saat butuh.', starter: { name: 'Pemula', price: '$19', period: '/bulan', tokens: '50,000 AI tokens', videos: '5 video', files: '3 file merek', support: 'Dukungan email' }, pro: { name: 'Pro', price: '$49', period: '/bulan', tokens: '200,000 AI tokens', videos: '20 video', files: '10 file merek', support: 'Dukungan email prioritas', badge: 'Paling Populer' }, enterprise: { name: 'Enterprise', price: 'Kustom', cta: 'Hubungi Kami', tokens: 'AI tokens tak terbatas', videos: 'Video tak terbatas', files: 'File merek tak terbatas', support: 'Dukungan khusus' }, cta: 'Mulai' },
  tokens: { title: 'Butuh Token Lebih?', subtitle: 'Bayar sesuai penggunaan. Token tidak kedaluwarsa.', small: { name: 'Paket Kecil', price: '$9', tokens: '20,000 tokens' }, medium: { name: 'Paket Sedang', price: '$19', tokens: '50,000 tokens' }, large: { name: 'Paket Besar', price: '$39', tokens: '120,000 tokens' }, cta: 'Beli Sekarang' },
  contact: { title: 'Hubungi Penjualan Enterprise', name: 'Nama Lengkap', email: 'Alamat Email', message: 'Ceritakan kebutuhan Anda', submit: 'Kirim Pesan', success: 'Pesan terkirim! Kami akan membalas dalam 24 jam.', error: 'Gagal terkirim.' },
  footer: { rights: '© 2026 AI Marketing OS. Hak cipta dilindungi.', contact: 'Hubungi' },
}
