export default {
  nav: { features: 'Ciri-ciri', pricing: 'Harga', login: 'Log Masuk', getStarted: 'Mulakan Percuma' },
  hero: { title: 'Tukar Mana-mana Halaman Facebook Kepada Iklan Bertukar Tinggi — Dalam Minit', subtitle: 'Alat pemasaran berkuasa AI untuk pengiklan Facebook, pencipta video, dan penyiar langsung.', cta: 'Mulakan Percuma', ctaSub: 'Tiada kad kredit diperlukan' },
  features: { title: 'Semua Yang Anda Perlukan', analysis: { title: 'Analisis Halaman', desc: 'Analisis mana-mana halaman Facebook dengan AI.' }, copy: { title: 'Penjana Salinan', desc: 'Jana 2 versi tajuk, badan, dan CTA.' }, landing: { title: 'Pembina Halaman', desc: 'Buat halaman HTML lengkap dengan pratonton.' }, video: { title: 'Jana Video', desc: 'Cipta video AI untuk kandungan produk.' } },
  pricing: { title: 'Harga Mudah & Telus', subtitle: 'Mulakan percuma, naik taraf bila perlu.', starter: { name: 'Pemula', price: '$19', period: '/bulan', tokens: '50,000 token AI', videos: '5 jana video', files: '3 fail jenama', support: 'Sokongan e-mel' }, pro: { name: 'Pro', price: '$49', period: '/bulan', tokens: '200,000 token AI', videos: '20 jana video', files: '10 fail jenama', support: 'Sokongan e-mel keutamaan', badge: 'Paling Popular' }, enterprise: { name: 'Perusahaan', price: 'Tersuai', cta: 'Hubungi Kami', tokens: 'Token AI tanpa had', videos: 'Jana video tanpa had', files: 'Fail jenama tanpa had', support: 'Sokongan dedikasi' }, cta: 'Mulakan' },
  tokens: { title: 'Perlu Lebih Token?', subtitle: 'Bayar mengikut penggunaan. Token tidak luput.', small: { name: 'Pek Kecil', price: '$9', tokens: '20,000 token' }, medium: { name: 'Pek Sederhana', price: '$19', tokens: '50,000 token' }, large: { name: 'Pek Besar', price: '$39', tokens: '120,000 token' }, cta: 'Beli Sekarang' },
  contact: { title: 'Hubungi Jualan Perusahaan', name: 'Nama Penuh', email: 'Alamat E-mel', message: 'Beritahu kami keperluan anda', submit: 'Hantar Mesej', success: 'Mesej dihantar! Kami akan membalas dalam 24 jam.', error: 'Gagal dihantar.' },
  footer: { rights: '© 2026 AI Marketing OS. Hak cipta terpelihara.', contact: 'Hubungi' },
}
