export default {
  nav: { features: 'Tinh nang', pricing: 'Bang gia', login: 'Dang nhap', getStarted: 'Bat dau mien phi' },
  hero: { title: 'Bien Bat Ky Trang Facebook Nao Thanh Quang Cao Chuyen Doi Cao — Trong Vai Phut', subtitle: 'Cong cu marketing AI cho nha quang cao Facebook, nguoi sang tao video va nguoi livestream.', cta: 'Bat dau mien phi', ctaSub: 'Khong can the tin dung' },
  features: { title: 'Moi Thu Ban Can', analysis: { title: 'Phan Tich Trang', desc: 'Phan tich trang Facebook voi AI.' }, copy: { title: 'Tao Noi Dung', desc: 'Tao 2 phien ban tieu de, noi dung va CTA.' }, landing: { title: 'Xay Dung Landing Page', desc: 'Tao trang HTML day du voi xem truoc.' }, video: { title: 'Tao Video', desc: 'Tao video AI cho san pham.' } },
  pricing: { title: 'Bang Gia Don Gian & Minh Bach', subtitle: 'Bat dau mien phi, nang cap khi can.', starter: { name: 'Co Ban', price: '$19', period: '/thang', tokens: '50,000 AI tokens', videos: '5 video', files: '3 tep thuong hieu', support: 'Ho tro email' }, pro: { name: 'Chuyen Nghiep', price: '$49', period: '/thang', tokens: '200,000 AI tokens', videos: '20 video', files: '10 tep thuong hieu', support: 'Ho tro email uu tien', badge: 'Pho bien nhat' }, enterprise: { name: 'Doanh Nghiep', price: 'Tuy chinh', cta: 'Lien he', tokens: 'AI tokens khong gioi han', videos: 'Video khong gioi han', files: 'Tep thuong hieu khong gioi han', support: 'Ho tro rieng' }, cta: 'Bat dau' },
  tokens: { title: 'Can Them Token?', subtitle: 'Tra theo su dung. Token khong het han.', small: { name: 'Goi Nho', price: '$9', tokens: '20,000 tokens' }, medium: { name: 'Goi Vua', price: '$19', tokens: '50,000 tokens' }, large: { name: 'Goi Lon', price: '$39', tokens: '120,000 tokens' }, cta: 'Mua ngay' },
  contact: { title: 'Lien He Ban Hang Doanh Nghiep', name: 'Ho va ten', email: 'Dia chi email', message: 'Cho chung toi biet nhu cau cua ban', submit: 'Gui tin nhan', success: 'Da gui! Chung toi se phan hoi trong 24 gio.', error: 'Gui that bai.' },
  footer: { rights: '© 2026 AI Marketing OS. Bao luu moi quyen.', contact: 'Lien he' },
}
